apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  INVENTORY_DB_USER: CHANGE_ME
  INVENTORY_DB_PASSWORD: CHANGE_ME
  INVENTORY_DB_NAME: CHANGE_ME

  ORDER_DB_USER: CHANGE_ME
  ORDER_DB_PASSWORD: CHANGE_ME
  ORDER_DB_NAME: CHANGE_ME

  GIT_USERNAME: CHANGE_ME
  GIT_TOKEN: CHANGE_ME